[package]
name = "xmpl"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"
actix-web-static-files = "3"
static-files = "0.2.1"

[build-dependencies]
static-files = "0.2.1"
